// Generated by CoffeeScript 1.6.3
define(['cell/Resource'], function(Resource) {
  return new Resource({
    url: 'https://api.mongolab.com/api/1/databases/testpeterwmwong/collections/poll-results/{id}?apiKey=4cIC7N8HM4TTAeOHVNrR3CstB1eGJQ7z&q={q}',
    params: {
      id: '',
      q: ''
    }
  });
});

/*
//@ sourceMappingURL=PollResults.map
*/
