// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Collection, Resource;
  Resource = require('cell/Resource');
  Collection = require('cell/Collection');
  return new Resource({
    url: 'https://api.mongolab.com/api/1/databases/testpeterwmwong/collections/polls/{id}?apiKey=4cIC7N8HM4TTAeOHVNrR3CstB1eGJQ7z',
    params: {
      id: ''
    },
    transform: function(obj) {
      obj.choices = new Collection(obj.choices);
      return obj;
    }
  });
});

/*
//@ sourceMappingURL=Polls.map
*/
