// Generated by CoffeeScript 1.6.3
define(function() {
  return function(_arg) {
    var beforeEachRequire;
    beforeEachRequire = _arg.beforeEachRequire;
    beforeEachRequire(['views/MyView'], function(MyView) {
      this.MyView = MyView;
    });
    return describe('When MyView is rendered', function() {
      beforeEach(function() {
        return this.el = new this.MyView().el;
      });
      return it('it renders "Hello from MyView!"', function() {
        return expect(this.el.textContent).toBe('Hello from MyView!');
      });
    });
  };
});

/*
//@ sourceMappingURL=MyView.spec.map
*/
