// Generated by CoffeeScript 1.6.3
define(function(require) {
  var App, Poll, Polls, events;
  Polls = require('views/Polls');
  Poll = require('views/Poll');
  events = require('cell/dom/events');
  App = require('cell/defineView!')({
    beforeRender: function() {
      this.set('selectedPoll', '');
      events.on(window, 'hashchange', this.updatedSelectedPoll, this);
      return this.updatedSelectedPoll();
    },
    renderEl: function() {
      return document.body;
    },
    render: function(_) {
      return [
        function() {
          var pollid;
          if (pollid = this.get('selectedPoll')) {
            return _(Poll, {
              pollId: pollid
            });
          } else {
            return _(Polls);
          }
        }
      ];
    },
    updatedSelectedPoll: function() {
      var _ref;
      this.set('selectedPoll', (_ref = /^\/?#\/(.*)/.exec(window.location.hash)) != null ? _ref[1] : void 0);
    }
  });
  return new App();
});

/*
//@ sourceMappingURL=App.map
*/
