// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

define(['require', './GENERATED_all-specs'], function(require, allSpecs) {
  return require(allSpecs, function() {
    var jasmineEnv, spec, specs, trivialReporter, _i, _len;
    specs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    for (_i = 0, _len = specs.length; _i < _len; _i++) {
      spec = specs[_i];
      spec();
    }
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 5000;
    if (window.__karma__ != null) {
      return window.__karma__.start();
    } else {
      trivialReporter = new jasmine.TrivialReporter();
      jasmineEnv.addReporter(trivialReporter);
      jasmineEnv.specFilter = function(spec) {
        return trivialReporter.specFilter(spec);
      };
      return jasmineEnv.execute();
    }
  });
});

/*
//@ sourceMappingURL=SpecRunner.map
*/
